services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=lol'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_USER=riot'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    hostname: redis
    ports:
      - '${REDIS_PORT}:6379'
